{
 "title": "My public RPC proxy",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Request count by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(rpc_requests_total[$__rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Bytes sent by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(rpc_byte_size_sum[$__rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(le) (rate(rpc_byte_size_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg by(le) (rate(rpc_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}